stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xinzhilv/admin:0.{CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.cn-shenzhen.aliyuncs.com
timeout: 60
notification: {}
